### ISSUE TITLE
HostedCE needs cron for fetchcrl

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-catalog#149]
The HostedCE container needs a crond running under supervisord, such that it can periodically run fetchcrl and keep certs up to date.

This needs to be added into the supervisor config:

```
[program:crond]
command=/usr/sbin/crond -n
autorestart=true
```

and we need a corresponding cronjob for running `fetchcrl`

**Comment by Mansalu** [comment]
This has been done.
