### ISSUE TITLE
Minio needs improvement

### ISSUE THREAD

**Issue by Mansalu** [slateci/slate-catalog#154]
- Documentation should explain how to properly create a SLATE secret with both keys, and connect to values.

- There are additional files that can be removed from the container image
   See: https://github.com/slateci/slate-catalog/pull/153

- We should modify the git clone in the minio dockerfile to point at release tags

- There is additional/unwanted functionality in the chart that should be removed
      * Multiple ways to create buckets
      * Statefulset that deploys the client
      * TLS ???
      * Others ???

**Comment by Mansalu** [comment]
@cnweaver Feel free to provide input here, particularly on the TLS stuff. I'm creating an issue for all this so I can keep track of everything.

**Comment by Mansalu** [comment]
Removal of source files has been completed. 

https://github.com/slateci/slate-catalog/pull/155

**Comment by cnweaver** [comment]
I think that we will want to keep the TLS stuff. One way to do that is by using the ingress controller and cert-manager (which I have tested with other applications on uchicago-prod but not yet done anything to make more generally available), but the chart's ability to do its own TLS with certificates brought by the user seems like it's also nice to have; we should just make it clear to users that they don't have to use it, and can get automatic certs (once we have cert-manager everywhere). 

The dockerfile git cloning release tags stuff may also involve switching to the dockerfile.release, although I have not yet read closely what that version does differently.

**Comment by Mansalu** [comment]
OK, it sounds like some additional discussion is needed on these points.

**Comment by Mansalu** [comment]
This is completed.
