### ISSUE TITLE
Hosted CE should use k8s-standard cert names

### ISSUE THREAD

**Issue by bbockelm** [slateci/slate-catalog#339]
In the secret for the credentials (`HostCredentials` section in the yaml), we currently reference one file (`host.key`) in one secret for the cert and a second file (`host.cert`) in a second secret for the key.

Unfortunately, certificates produced by a tool like cert-manager (https://cert-manager.io/docs/usage/certificate/) appear to hardcode the more common names of `tls.crt` and `tls.key`.

Would it be possible to extend the chart to switch to these names for the files?  I don't think `tls.crt` and `tls.key` are written-down standards but rather what everyone else appears to use.

**Comment by Mansalu** [comment]
Yes, I think this can be reworked.

**Comment by bbockelm** [comment]
For reference - I'm aiming to have this be compatible with secrets of type `kubernetes.io/tls`.

**Comment by Mansalu** [comment]
Closed by https://github.com/slateci/slate-catalog/pull/344
