### ISSUE TITLE
Add external-dns annotations in the osg-hosted-ce chart

### ISSUE THREAD

**Issue by bbockelm** [slateci/slate-catalog#342]
Outside SLATE, we use `external-dns` for integration with DNS.  Can we add the appropriate annotation to the `Service` generated for the CE?

Looks something like this:
```
...
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hosted-ce1.svcs.opensciencegrid.org
...
```

**Comment by Mansalu** [comment]
We can add the annotation.
