### ISSUE TITLE
normalize configuration of x509 certificates

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-catalog#348]
Currently we don't create x509 certificates in a consistent way.

For example, the gridftp application creates a secret called x509-certificates and dumps them into a directory, where the container then picks them up and manipulates them appropriately. For example, the invocation for GridFTP looks something like this:
```
slate secret create <--flags> secretname --from-file=hostcert.pem --from-file=hostkey.pem
```

XCache creates a secret with named keys and paths, which changes the invocation of the `slate secret` command. So it's invocation looks like this:
```
slate secret create <--flags> secretname --from-file=usercert=usercert.pem --from-file=userkey=userkey.pem
```

We need to normalize these into ONE configuration that will work for SLATE, so the interface is consistent.

**Comment by robrwg** [comment]
Muhammad can you have a look?

**Comment by Mansalu** [comment]
Isn't this being worked on by Soundar, already?

#429

**Comment by rajends-umich** [comment]
Yes it was worked on by me. Was waiting on my changes being tested by Lincoln. Lost track of it during the holidays. Now I have created a PR for my branch. Lincoln said he will test it

**Comment by LincolnBryant** [comment]
I think this works, - will reopen if there are troubles.
