### ISSUE TITLE
Logger Side Car Cannot Use Slate Secret

### ISSUE THREAD

**Issue by ghost** [slateci/slate-catalog#377]
https://github.com/slateci/slate-catalog/blob/c9d271f3d2fd9919ed2e831dfebce7df9c97b55c/stable/osg-hosted-ce/osg-hosted-ce/templates/configmap.yaml#L149-L160

When using a slate secret, to set the logger web password, it gets added to the file system in plain text instead of hashed like the randomly generated one is.  The webserver is expecting a hashed password so log in attempts with the correct password do not work.

I beleive a fix would look something like this:
```bash
if [ -z $HTPASSWD ]; then
      HTPASSWD=$(tr -dc 'a-f0-9' < /dev/urandom | head -c16)
      echo "Your randomly generated logger credentials are"
      echo "**********************************************"
      echo "logger:$HTPASSWD"
      echo "**********************************************"
fi

# maybe validate this
mkdir -p /etc/nginx/auth
echo "logger:$(openssl passwd -apr1 $(echo -n $HTPASSWD))" > /etc/nginx/auth/htpasswd
```

**Comment by robrwg** [comment]
Muhammad can you address this?

**Comment by muali14** [comment]
Resolved. Please reach out if this is still an issue. Thanks!
