### ISSUE TITLE
Numeric instances are broken

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-catalog#47]
today I wanted to have slate make a bunch of instances of something, but didn't have "replicas" templated in my deployment. so instead i did something like this:
```
for i in {1..30}; do sed "s/Instance: global/Instance: $i/" htcondor.yaml > htcondor-$i.yaml ; done
```

such that Instance is `Instance: 1`, `Instance: 2`, ... 

but then I get an error:
```
Failed to install application htcondor: Failed to start application instance with helm:
Error: render error in "htcondor/templates/deployment.yaml": template: htcondor/templates/_helpers.tpl:16:16: executing "condor.fullname" at <$name>: wrong type for value; expected string; got float64

 system namespace: slate-system
```

quoting the number also doesn't work. putting a character with the number does, though.

**Comment by cnweaver** [comment]
This should be fixed throughout the stable catalog, but applications in incubator still need to be brought into compliance. The main change which is usually needed is to quote the instance tag when it appears without other data which would force it to be interpreted as a string, e.g changing

	someProp: {{ .Values.Instance }}

to

	someProp: {{ .Values.Instance | quote }}
